version: '3.4'

services:
  investapi:
    container_name: investapi
    image: iinvestapi
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile