// <auto-generated />
using Invest.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Invest.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Invest.Entities.Acao", b =>
                {
                    b.Property<string>("AcaoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("acao_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("razao_social");

                    b.HasKey("AcaoId");

                    b.ToTable("acao");
                });

            modelBuilder.Entity("Invest.Entities.Operacao", b =>
                {
                    b.Property<int>("OperacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcaoId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PrecoAcao")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperacaoId");

                    b.HasIndex("AcaoId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("Invest.Entities.Operacao", b =>
                {
                    b.HasOne("Invest.Entities.Acao", "acao")
                        .WithMany()
                        .HasForeignKey("AcaoId");

                    b.Navigation("acao");
                });
#pragma warning restore 612, 618
        }
    }
}
